# Preprocessing

In [1]:
import pandas as pd

data = pd.read_csv('hotel_bookings.csv')

data.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [3]:
data.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [4]:
data.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [5]:
data_preprocessed = data.copy()
data_preprocessed['children'] = data['children'].fillna(-1).astype(int)
data_preprocessed['arrival_date'] = pd.to_datetime(data.arrival_date_year.astype(str) + '-' + data.arrival_date_month.astype(str) + '-' + data.arrival_date_day_of_month.astype(str))
data_preprocessed['arrival_year'] = data_preprocessed['arrival_date'].dt.year
data_preprocessed['arrival_month'] = data_preprocessed['arrival_date'].dt.month
data_preprocessed['arrival_day'] = data_preprocessed['arrival_date'].dt.day
data_preprocessed.drop(['arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month','arrival_date'], axis=1, inplace=True)
data_preprocessed.drop(['agent', 'company'], axis=1, inplace = True)
data_preprocessed = pd.get_dummies(data_preprocessed, columns=['hotel'], drop_first=True)
data_preprocessed = pd.get_dummies(data_preprocessed, columns=['meal'], drop_first=True)
data_preprocessed = pd.get_dummies(data_preprocessed, columns=['country'], drop_first=True)
data_preprocessed = pd.get_dummies(data_preprocessed, columns=['market_segment'], drop_first=True)
data_preprocessed = pd.get_dummies(data_preprocessed, columns=['distribution_channel'], drop_first=True)

data_preprocessed['room_attribution'] = (data_preprocessed['reserved_room_type'] == data_preprocessed['assigned_room_type'])
data_preprocessed.drop(['reserved_room_type', 'assigned_room_type'], axis=1, inplace=True)

data_preprocessed = pd.get_dummies(data_preprocessed, columns=['deposit_type'], drop_first=True)
data_preprocessed = pd.get_dummies(data_preprocessed, columns=['customer_type'], drop_first=True)
data_preprocessed = pd.get_dummies(data_preprocessed, columns=['reservation_status'], drop_first=True)

data_preprocessed.drop(['reservation_status_date'], axis=1, inplace=True)

In [6]:
data_preprocessed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Columns: 219 entries, is_canceled to reservation_status_No-Show
dtypes: bool(1), float64(1), int32(1), int64(17), uint8(199)
memory usage: 39.6 MB

In [7]:
data_preprocessed.head()

,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,...,distribution_channel_TA/TO,distribution_channel_Undefined,room_attribution,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,reservation_status_Check-Out,reservation_status_No-Show
0,0,342,27,0,0,2,0,0,0,0,...,0,0,True,0,0,0,1,0,1,0
1,0,737,27,0,0,2,0,0,0,0,...,0,0,True,0,0,0,1,0,1,0
2,0,7,27,0,1,1,0,0,0,0,...,0,0,False,0,0,0,1,0,1,0
3,0,13,27,0,1,1,0,0,0,0,...,0,0,True,0,0,0,1,0,1,0
4,0,14,27,0,2,2,0,0,0,0,...,1,0,True,0,0,0,1,0,1,0

In [8]:
data_preprocessed.describe()

,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,...,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,reservation_status_Check-Out,reservation_status_No-Show
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,...,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,27.165173,0.927599,2.500302,1.856403,0.103853,0.007949,0.031912,0.087118,...,0.001617,0.819750,0.000042,0.122179,0.001357,0.004833,0.750591,0.210436,0.629584,0.010110
std,0.482918,106.863097,13.605138,0.998613,1.908286,0.579261,0.398606,0.097436,0.175767,0.844336,...,0.040174,0.384397,0.006471,0.327494,0.036811,0.069351,0.432673,0.407620,0.482918,0.100038
min,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,18.000000,16.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
50%,0.000000,69.000000,28.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
75%,1.000000,160.000000,38.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
max,1.000000,737.000000,53.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:

predictive_variables = [
    'lead_time', 'arrival_date_week_number', 'stays_in_weekend_nights',
    'stays_in_week_nights', 'adults', 'children', 'babies',
    'is_repeated_guest', 'previous_cancellations',
    'previous_bookings_not_canceled', 'booking_changes',
    'days_in_waiting_list', 'adr', 'required_car_parking_spaces',
    'total_of_special_requests', 'arrival_year', 'arrival_month', 
    'arrival_day', 'hotel_Resort Hotel', 'room_attribution',
    'deposit_type_Non Refund'    
]
existing_predictive_vars = [var for var in predictive_variables if var in data_preprocessed.columns]


df_input = data_preprocessed[existing_predictive_vars]
df_output = data_preprocessed['is_canceled']

<h1>Random Forest Classifier
</h1>

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV



X_train, X_test, y_train, y_test = train_test_split(df_input, df_output, test_size=0.2, random_state=42)

param_grid = {'n_estimators': list(range(10, 150, 10))}
rf = RandomForestClassifier(random_state=42)
clf = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, scoring='accuracy', n_jobs=-1)

best_n_estimators = clf.best_params_['n_estimators']
print(best_n_estimators)

clf.fit(X_train, y_train) 

y_pred = clf.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")


matriz_confusion = confusion_matrix(y_test, y_pred)


sns.heatmap(matriz_confusion, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.xlabel('PredicciÃ³n')
plt.ylabel('Realidad')
plt.title('Matriz de ConfusiÃ³n')
plt.show()

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

<h1>METRICAS</h1>

<h5>Accuracy: Muestra cuÃ¡ntas predicciones en total fueron correctas. Es una buena medida cuando las clases estÃ¡n balanceadas pero puede ser engaÃ±osa cuando hay un desbalance significativo entre las clases.</h5>
<h5>Recall: Especialmente importante cuando los falsos negativos son mÃ¡s crÃ­ticos que los falsos positivos. Por ejemplo, en la detecciÃ³n de enfermedades serÃ­a mÃ¡s perjudicial no detectar una enfermedad (falso negativo) que diagnosticarla por error (falso positivo).</h5>
<h5>Precision: Importante cuando los falsos positivos son mÃ¡s problemÃ¡ticos que los falsos negativos. Por ejemplo, en el filtrado de spam, podrÃ­a ser mÃ¡s problemÃ¡tico marcar un correo electrÃ³nico legÃ­timo como spam (falso positivo) que no marcar un spam (falso negativo).</h5>
<h5>F1 Score: Combina la precisiÃ³n y el recall en una sola mÃ©trica. Es Ãºtil cuando necesitas una medida que tenga en cuenta tanto los falsos positivos como los falsos negativos.</h5>

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_auc_score

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
# Asumimos que las clases son binarias: 0 para cancelaciones, 1 para no canceladas
classes = [0, 1]
class_labels = ['CancelaciÃ³n', 'No CancelaciÃ³n']

for class_ in classes:
    y_real = [1 if y == class_ else 0 for y in dfTestOutputs]
    y_pred_class = [1 if y == class_ else 0 for y in y_pred]
    score = precision_score(y_real, y_pred_class, zero_division=0)
    print(f'Precision for {class_labels[class_]}: {round(score, 6)}')

for class_ in classes:
    y_real = [1 if y == class_ else 0 for y in dfTestOutputs]
    y_pred_class = [1 if y == class_ else 0 for y in y_pred]
    score = recall_score(y_real, y_pred_class, zero_division=0)
    print(f'Recall for {class_labels[class_]}: {round(score, 6)}')

print(f"Accuracy: {accuracy:.2f}")
print(f"F1 Score: {f1:.2f}")

<h1>Cross-Validaton</h1>

In [ ]:
from sklearn.model_selection import cross_val_score

clf = RandomForestClassifier(n_estimators=100, random_state=42)
scores = cross_val_score(clf, df_input, df_output, cv=5, scoring='accuracy')
print("Accuracy scores for each fold:")
print(scores)
print(f"Average cross-validation accuracy: {scores.mean()}")